### ISSUE TITLE
Add variables to variables.tf

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/terraform-nomad-redash#4]
Add use of variables so that the module is a little more flexible when imported. A prime example is https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/variables.tf

**Comment by claesgill** [comment]
I was about to start on this issue when I realized that #21 restructure some of the code. So i think #21 should be merged before we proceed on this issue.

**Comment by pdmthorsrud** [comment]
I assume you still want to work on this issue, right? :)

**Comment by claesgill** [comment]
Yes, and I kinda started already :sweat_smile:
